name: benchmark
on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Forced run: set to -f'
        required: false
        default: ''
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: "4.0.2"

      - uses: actions/checkout@v2
        with:
          repository: lasp-lang/lasp-bench
          ref: d9b3e78d64ea4709ca10ec062c7fc969c1c503d4
          path: lasp-bench

      - uses: actions/checkout@v2
        with:
          repository: Nordix/eredis
          ref: master
          path: eredis

      - name: Current Erlang/OTP version
        run: erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell

      - name: Install Erlang/OTP
        run: |
          DEB_NAME="esl-erlang_23.1-1~ubuntu~focal_amd64.deb"
          curl -f https://packages.erlang-solutions.com/erlang/debian/pool/$DEB_NAME -o $DEB_NAME
          sudo dpkg --install $DEB_NAME

      - name: Run tests and commit results
        run: ./run-tests.sh ${{ github.event.inputs.force }}
