name: benchmark
on:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: "4.0.2"

      - name: Run tests and commit results
        run: ./run-tests.sh
